### ISSUE TITLE
Basic User Login

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#22]
- [x] Screen should be available on `/login`
- [x] Input fields: `userName` `password`
- [x] Use `/auth` endpoint

**Comment by THPubs** [comment]
Any plans to provide support for third party auth providers like `Firebase Auth`, `Cognito`, and `Auth0`?

**Comment by thinkholic** [comment]
@THPubs Yes, will include in the roadmap.

**Comment by thinkholic** [comment]
@THPubs Created a tracking issue for the feature suggestion. https://github.com/thinkholic/backdrop-js/issues/45
