### ISSUE TITLE
[STORY] As a user I want to setup a blog using Backdrop.js

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#51]
### v1
- [x] Should able to use CLI to bootstrap the project and configure
- [x] Create a resource for Posts, Comments
  - [x] Posts (`title: Text`, `slug: Text`, `content: RichText`, `comments: Resource`)
  - [x] Comments (`author: Text`, `email: Email`, `comment: Multiline`, `posts: Resource`) [private]
- [x] There should be multiple authors
- [x] I need to insert image to content from Media Library

**Comment by heimdallrhg** [comment]
### v2

- [ ] `slug` should be auto generated based on title

**Comment by thinkholic** [comment]
Done.
